import { LayoutBlock } from './layouts';
import { templateSites } from './templateSites';

export type FullTemplate = {
  id: string;
  label: string;
  description: string;
  category: string;
  pages: Array<{ name: string; slug: string; title: string; blocks: LayoutBlock[] }>;
  colors: [string, string, string, string, string, string, string];
};

const contactForm: LayoutBlock = { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'textarea', name: 'message', label: 'Bericht', required: true }], submit_text: 'Versturen', success_message: 'Bedankt, we nemen snel contact op.' } };

type TemplateLayout = 'editorial' | 'commerce' | 'fitness' | 'property' | 'consultant' | 'technology' | 'product' | 'magazine' | 'story' | 'local';

function standardPages(hero: string, intro: string, services: string[], accent: LayoutBlock[] = [], layout: TemplateLayout = 'consultant', brand = 'Jouw merk'): FullTemplate['pages'] {
  const header = (links: Array<{ label: string; url: string }>, ctaText: string, ctaUrl = '/contact'): LayoutBlock => ({ type: 'header', content: { logo: brand, links, cta_text: ctaText, cta_url: ctaUrl } });
  const footer = (): LayoutBlock => ({ type: 'footer', content: { text: `${brand} - ${intro}`, links: [{ label: 'Privacy', url: '#' }, { label: 'Contact', url: '/contact' }] } });
  const serviceCards = services.map(title => ({ type: 'card', content: { title, description: `Ontdek hoe ${title.toLowerCase()} je helpt om sneller en beter resultaat te behalen.`, cta_text: 'Lees meer', cta_url: '/diensten' } } as LayoutBlock));
  const homeLayouts: Record<TemplateLayout, LayoutBlock[]> = {
    editorial: [header([{ label: 'Portfolio', url: '/diensten' }, { label: 'Over ons', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Boek een shoot'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Bekijk portfolio', cta_url: '/diensten', text_align: 'left' } }, { type: 'gallery', content: { images: [], columns: 3, gap: '1rem' } }, { type: 'heading', content: { level: 'h2', text: 'Diensten' } }, ...serviceCards, footer()],
    commerce: [header([{ label: 'Collectie', url: '/diensten' }, { label: 'Bestsellers', url: '/diensten' }, { label: 'Contact', url: '/contact' }], 'Bekijk collectie', '/diensten'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Shop de collectie', cta_url: '/diensten', text_align: 'center' } }, { type: 'heading', content: { level: 'h2', text: 'Favorieten uit de collectie' } }, ...serviceCards, { type: 'pricing', content: { title: 'Voordelige bundels', plans: [{ name: 'Starter', price: '€29', features: ['3 zorgvuldig gekozen items', 'Snelle verzending'], cta_text: 'Bekijk bundel', cta_url: '/diensten' }, { name: 'Complete set', price: '€79', features: ['8 items voor thuis', 'Gratis verzending'], cta_text: 'Bekijk bundel', cta_url: '/diensten' }] } }, footer()],
    fitness: [header([{ label: 'Trainingen', url: '/diensten' }, { label: 'Lidmaatschappen', url: '/diensten' }, { label: 'Contact', url: '/contact' }], 'Start vandaag'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Start je training', cta_url: '/contact', text_align: 'left' } }, { type: 'heading', content: { level: 'h2', text: 'Train op jouw manier' } }, ...serviceCards, { type: 'pricing', content: { title: 'Kies je lidmaatschap', plans: [{ name: 'Basis', price: '€39 p/m', features: ['Onbeperkt trainen'], cta_text: 'Start vandaag', cta_url: '/contact' }, { name: 'Plus', price: '€69 p/m', features: ['Onbeperkt trainen', '2 coachsessies'], cta_text: 'Kies Plus', cta_url: '/contact' }] } }, { type: 'testimonials', content: { title: 'Dit zeggen onze leden', items: [{ quote: 'Ik train sterker en consistenter dan ooit.', name: 'Daan Smit', role: 'Lid sinds 2024' }] } }, footer()],
    property: [header([{ label: 'Woningen', url: '/diensten' }, { label: 'Verkopen', url: '/diensten' }, { label: 'Over ons', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Plan een waardebepaling'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Bekijk ons aanbod', cta_url: '/diensten', text_align: 'left' } }, { type: 'heading', content: { level: 'h2', text: 'Waarmee we helpen' } }, ...serviceCards, { type: 'blog', content: { title: 'Woningmarkt in beweging', posts: [{ title: 'Je woning verkoopklaar maken', excerpt: 'Praktische tips voor een sterke eerste indruk.', date: '12 juni 2026', url: '/diensten' }, { title: 'Een huis kopen met vertrouwen', excerpt: 'Zo bereid je je goed voor op de volgende stap.', date: '4 juni 2026', url: '/diensten' }] } }, footer()],
    consultant: [header([{ label: 'Diensten', url: '/diensten' }, { label: 'Over ons', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Plan een gesprek'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Ontdek mijn aanpak', cta_url: '/diensten', text_align: 'left' } }, { type: 'heading', content: { level: 'h2', text: 'Waar ik je bij help' } }, ...serviceCards, { type: 'testimonials', content: { title: 'Samenwerken in de praktijk', items: [{ quote: 'De combinatie van scherp advies en daadkracht maakte direct verschil.', name: 'Sanne de Vries', role: 'Klant' }] } }, { type: 'cta', content: { title: 'Een vraagstuk op tafel?', text: 'Plan een kort gesprek om te verkennen wat er nodig is.', button_text: 'Plan een gesprek', button_url: '/contact' } }, footer()],
    technology: [header([{ label: 'Oplossingen', url: '/diensten' }, { label: 'Onze aanpak', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Plan een security scan'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Bekijk oplossingen', cta_url: '/diensten', text_align: 'left' } }, { type: 'dashboard', content: { title: 'Technologie met meetbaar resultaat', notice: 'Alle systemen operationeel.', stats: [{ label: 'Uptime', value: '99,99%', change: 'Betrouwbaar' }, { label: 'Klanttevredenheid', value: '9,4' }, { label: 'Actieve projecten', value: '38' }] } }, { type: 'heading', content: { level: 'h2', text: 'Onze expertise' } }, ...serviceCards, { type: 'faq', content: { title: 'Veelgestelde vragen', items: [{ question: 'Kunnen jullie bestaande systemen beheren?', answer: 'Ja, we sluiten aan op je huidige infrastructuur en team.' }, { question: 'Hoe snel kunnen we starten?', answer: 'Na een korte intake maken we een concreet startplan.' }] } }, footer()],
    product: [header([{ label: 'Product', url: '/diensten' }, { label: 'Prijzen', url: '/diensten' }, { label: 'Contact', url: '/contact' }], 'Start gratis', '/diensten'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Probeer gratis', cta_url: '/diensten', text_align: 'center' } }, { type: 'heading', content: { level: 'h2', text: 'Alles op een plek' } }, ...serviceCards, { type: 'pricing', content: { title: 'Kies een plan dat meegroeit', plans: [{ name: 'Free', price: '€0', features: ['Voor kleine teams'], cta_text: 'Probeer gratis', cta_url: '/diensten' }, { name: 'Team', price: '€12 p/u', features: ['Onbeperkte projecten', 'Teamrapportages'], cta_text: 'Start trial', cta_url: '/diensten' }, { name: 'Scale', price: 'Op maat', features: ['SLA support', 'Geavanceerde beveiliging'], cta_text: 'Praat met sales', cta_url: '/contact' }] } }, { type: 'faq', content: { title: 'Vragen over het product', items: [{ question: 'Kan ik gratis starten?', answer: 'Ja, zonder betaalgegevens.' }, { question: 'Kan ik later upgraden?', answer: 'Je kunt op elk moment van plan veranderen.' }] } }, footer()],
    magazine: [header([{ label: 'Artikelen', url: '/diensten' }, { label: 'Themas', url: '/diensten' }, { label: 'Redactie', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Blijf op de hoogte', '/contact'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Lees de nieuwste verhalen', cta_url: '/diensten', text_align: 'left' } }, { type: 'blog', content: { title: 'Uitgelicht', posts: [{ title: 'Een goed begin', excerpt: 'Waarom kleine stappen vaak de grootste verandering brengen.', date: '12 juni 2026', url: '/diensten' }, { title: 'Achter het verhaal', excerpt: 'Maak kennis met de mensen en ideeen achter de artikelen.', date: '5 juni 2026', url: '/diensten' }, { title: 'Praktijk voor elke dag', excerpt: 'Inspiratie die je meteen kunt gebruiken.', date: '28 mei 2026', url: '/diensten' }] } }, { type: 'heading', content: { level: 'h2', text: 'Onze themas' } }, ...serviceCards, footer()],
    story: [header([{ label: 'Mijn verhaal', url: '/over-ons' }, { label: 'Mijn werk', url: '/diensten' }, { label: 'Notities', url: '/diensten' }, { label: 'Contact', url: '/contact' }], 'Neem contact op'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Lees mijn verhaal', cta_url: '/over-ons', text_align: 'left' } }, { type: 'text', content: { content: 'Een persoonlijke plek voor werk, verhalen en inspiratie. Kijk rustig rond en ontdek wat mij bezighoudt.' } }, { type: 'heading', content: { level: 'h2', text: 'Waar ik aan werk' } }, ...serviceCards, { type: 'testimonials', content: { title: 'Fijne samenwerkingen', items: [{ quote: 'Een creatieve en betrouwbare partner die goed luistert.', name: 'Ruben Bakker', role: 'Samenwerkingspartner' }] } }, footer()],
    local: [header([{ label: 'Aanbod', url: '/diensten' }, { label: 'Openingstijden', url: '/diensten' }, { label: 'Over ons', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Kom langs'), { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Bekijk ons aanbod', cta_url: '/diensten', text_align: 'center' } }, { type: 'heading', content: { level: 'h2', text: 'Persoonlijke service, dichtbij' } }, ...serviceCards, { type: 'faq', content: { title: 'Praktische informatie', items: [{ question: 'Wanneer zijn jullie open?', answer: 'Maandag tot en met zaterdag van 09:00 tot 18:00.' }, { question: 'Kan ik vooraf bestellen?', answer: 'Ja, neem telefonisch of via het formulier contact op.' }] } }, { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'textarea', name: 'message', label: 'Waar kunnen we mee helpen?' }], submit_text: 'Stuur een bericht', success_message: 'Bedankt, we nemen snel contact op.' } }, footer()]
  };
  const pageVariants: Record<TemplateLayout, FullTemplate['pages']> = {
    editorial: [
      { name: 'Over ons', slug: 'over-ons', title: 'Werkwijze', blocks: [header([{ label: 'Portfolio', url: '/diensten' }, { label: 'Over ons', url: '/over-ons' }, { label: 'Contact', url: '/contact' }], 'Boek een shoot'), { type: 'heading', content: { level: 'h1', text: 'Een beeld ontstaat in samenwerking' } }, { type: 'gallery', content: { images: [], columns: 2, gap: '1.5rem' } }, { type: 'text', content: { content: 'Van eerste briefing tot laatste selectie: we zoeken naar beelden met karakter, licht en een verhaal.' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Fotografie', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Fotografie voor merken en mensen' } }, { type: 'gallery', content: { images: [], columns: 3, gap: '.75rem' } }, ...serviceCards, { type: 'button', content: { text: 'Bespreek je productie', url: '/contact', variant: 'primary', size: 'lg' } }] },
      { name: 'Contact', slug: 'contact', title: 'Contact', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Vertel ons je verhaal' } }, { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'textarea', name: 'message', label: 'Over de shoot', required: true }], submit_text: 'Plan een kennismaking', success_message: 'We nemen snel contact op.' } }] }
    ],
    commerce: [
      { name: 'Over ons', slug: 'over-ons', title: 'Ons verhaal', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Mooie producten, bewust gekozen' } }, { type: 'text', content: { content: 'We selecteren items die lang meegaan, goed voelen en passen bij een dagelijks ritueel.' } }, { type: 'testimonials', content: { title: 'Klanten over Morrow', items: [{ quote: 'Snelle levering en precies de kwaliteit die ik zocht.', name: 'Nina de Wit', role: 'Klant' }] } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Collectie', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Ontdek de collectie' } }, { type: 'blog', content: { title: 'Nieuw binnen', posts: [{ title: 'Zomerse favorieten', excerpt: 'Lichte materialen en kleuren voor elke dag.', date: 'Nieuw', url: '#' }, { title: 'Cadeaus met aandacht', excerpt: 'Bundels voor bijzondere momenten.', date: 'Uitgelicht', url: '#' }] } }, ...serviceCards, { type: 'pricing', content: { title: 'Bundelvoordeel', plans: [{ name: 'Duo', price: '€49', features: ['2 favorieten', 'Verpakt als cadeau'], cta_text: 'Kies Duo', cta_url: '#' }, { name: 'Family', price: '€89', features: ['5 favorieten', 'Gratis verzending'], cta_text: 'Kies Family', cta_url: '#' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Service', blocks: [{ type: 'heading', content: { level: 'h1', text: 'We helpen je kiezen' } }, { type: 'faq', content: { title: 'Veel gevraagd', items: [{ question: 'Hoe snel wordt mijn bestelling geleverd?', answer: 'Binnen twee werkdagen.' }, { question: 'Kan ik retourneren?', answer: 'Ja, binnen dertig dagen.' }] } }, contactForm] }
    ],
    fitness: [
      { name: 'Over ons', slug: 'over-ons', title: 'Onze community', blocks: [{ type: 'hero', content: { headline: 'Sterker samen', subheadline: 'Een coach en community die je helpen volhouden.', cta_text: 'Maak kennis', cta_url: '/contact', text_align: 'left' } }, { type: 'testimonials', content: { title: 'Resultaten uit de community', items: [{ quote: 'De energie in de groep houdt me gemotiveerd.', name: 'Lisa Jansen', role: 'Lid' }, { quote: 'Elke training voelt als een stap vooruit.', name: 'Omar El Amrani', role: 'Lid' }] } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Trainingen', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Kies jouw trainingsritme' } }, { type: 'card', content: { title: 'Rooster', description: 'Bekijk de lessen van deze week en reserveer je plek.' } }, ...serviceCards, { type: 'pricing', content: { title: 'Lidmaatschappen', plans: [{ name: 'Basis', price: '€39 p/m', features: ['Onbeperkt trainen', 'App toegang'], cta_text: 'Start vandaag', cta_url: '/contact' }, { name: 'Coach', price: '€89 p/m', features: ['Onbeperkt trainen', 'Wekelijkse coaching'], cta_text: 'Kies Coach', cta_url: '/contact' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Proeftraining', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Plan je proeftraining' } }, { type: 'text', content: { content: 'Laat je gegevens achter. We bellen je om een passend moment te vinden.' } }, contactForm] }
    ],
    property: [
      { name: 'Over ons', slug: 'over-ons', title: 'Over ons', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Lokale kennis, persoonlijke aandacht' } }, { type: 'text', content: { content: 'We kennen de buurten, zien kansen en begeleiden je rustig door iedere beslissing.' } }, { type: 'stats', content: { items: [{ label: 'Jaar ervaring', value: '18+' }, { label: 'Verkochte woningen', value: '420' }, { label: 'Tevreden klanten', value: '98%' }] } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Woningen', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Vind je volgende plek' } }, { type: 'card', content: { title: 'Nieuwe woning', description: 'Ontdek woningen die passen bij jouw woonwensen.', cta_text: 'Bekijk aanbod', cta_url: '#' } }, { type: 'card', content: { title: 'Waardebepaling', description: 'Krijg inzicht in de actuele waarde van je woning.', cta_text: 'Vraag aan', cta_url: '/contact' } }, { type: 'blog', content: { title: 'Marktinzichten', posts: [{ title: 'Kopen in deze markt', excerpt: 'Een helder stappenplan voor kopers.', date: '12 juni 2026', url: '#' }, { title: 'Verkoop met voorbereiding', excerpt: 'Zo presenteer je je huis sterk.', date: '4 juni 2026', url: '#' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Afspraak', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Zullen we kennismaken?' } }, { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'text', name: 'interest', label: 'Ik wil...', required: true }, { type: 'textarea', name: 'message', label: 'Bericht' }], submit_text: 'Plan afspraak', success_message: 'We nemen snel contact op.' } }] }
    ],
    consultant: [
      { name: 'Over ons', slug: 'over-ons', title: 'Mijn aanpak', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Van vraagstuk naar beweging' } }, { type: 'text', content: { content: 'Ik breng structuur in complexe vragen en werk samen met de mensen die het verschil maken.' } }, { type: 'card', content: { title: '1. Verkennen', description: 'We maken het vraagstuk scherp.' } }, { type: 'card', content: { title: '2. Bouwen', description: 'We vertalen inzichten naar actie.' } }, { type: 'card', content: { title: '3. Leren', description: 'We meten wat werkt en verbeteren.' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Expertise', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Waar ik waarde toevoeg' } }, { type: 'pricing', content: { title: 'Samenwerken op maat', plans: [{ name: 'Sessie', price: '€450', features: ['2 uur focus', 'Direct actieplan'], cta_text: 'Plan sessie', cta_url: '/contact' }, { name: 'Traject', price: 'Op maat', features: ['Vaste begeleiding', 'Strategie en uitvoering'], cta_text: 'Bespreek traject', cta_url: '/contact' }] } }, ...serviceCards] },
      { name: 'Contact', slug: 'contact', title: 'Kennismaken', blocks: [{ type: 'cta', content: { title: 'Een goed gesprek begint hier', text: 'Vertel waar je tegenaan loopt.', button_text: 'Plan een gesprek', button_url: '#form' } }, { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'textarea', name: 'message', label: 'Waar wil je beweging in?', required: true }], submit_text: 'Versturen', success_message: 'Bedankt, ik neem contact op.' } }] }
    ],
    technology: [
      { name: 'Over ons', slug: 'over-ons', title: 'Engineering culture', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Complexiteit wordt eenvoud' } }, { type: 'dashboard', content: { title: 'Operationeel overzicht', stats: [{ label: 'Incidenten', value: '0', change: 'Deze maand' }, { label: 'Automations', value: '126' }, { label: 'Response', value: '14 min' }] } }, { type: 'text', content: { content: 'We ontwerpen systemen die veilig, uitlegbaar en klaar voor groei zijn.' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Oplossingen', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Een sterkere technische basis' } }, { type: 'card', content: { title: 'Cloud architecture', description: 'Schaalbare infrastructuur voor kritieke processen.' } }, { type: 'card', content: { title: 'Security operations', description: 'Bescherm data, systemen en vertrouwen.' } }, { type: 'card', content: { title: 'Data platforms', description: 'Maak informatie bruikbaar voor beslissingen.' } }, { type: 'faq', content: { title: 'Technische vragen', items: [{ question: 'Kunnen jullie met ons team samenwerken?', answer: 'Ja, we vullen bestaande teams aan.' }, { question: 'Hoe starten we?', answer: 'Met een technische intake en prioriteitenkaart.' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Technical briefing', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Plan een technische intake' } }, { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'Werk e-mail', required: true }, { type: 'text', name: 'company', label: 'Organisatie' }, { type: 'textarea', name: 'message', label: 'Technische uitdaging', required: true }], submit_text: 'Verstuur briefing', success_message: 'We nemen snel contact op.' } }] }
    ],
    product: [
      { name: 'Over ons', slug: 'over-ons', title: 'Waarom Flowdesk', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Minder administratie. Meer voortgang.' } }, { type: 'card', content: { title: 'Gemaakt voor teams', description: 'Een rustige werkplek voor plannen, taken en inzichten.' } }, { type: 'testimonials', content: { title: 'Teams die vooruitgaan', items: [{ quote: 'Iedereen weet wat de volgende stap is.', name: 'Eva Meijer', role: 'COO' }] } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Features & prijzen', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Alles wat je team nodig heeft' } }, { type: 'card', content: { title: 'Slimme planning', description: 'Van idee naar duidelijke acties.' } }, { type: 'card', content: { title: 'Teamruimte', description: 'Werk samen met context op één plek.' } }, { type: 'card', content: { title: 'Inzichten', description: 'Zie waar tijd en aandacht naartoe gaan.' } }, { type: 'pricing', content: { title: 'Eenvoudige prijzen', plans: [{ name: 'Free', price: '€0', features: ['Tot 3 gebruikers'], cta_text: 'Probeer gratis', cta_url: '#' }, { name: 'Team', price: '€12 p/u', features: ['Onbeperkte projecten'], cta_text: 'Start trial', cta_url: '#' }, { name: 'Scale', price: 'Op maat', features: ['SLA en security'], cta_text: 'Praat met sales', cta_url: '/contact' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Starten', blocks: [{ type: 'faq', content: { title: 'Vragen voor je start', items: [{ question: 'Is er een gratis proefperiode?', answer: 'Ja, je kunt zonder betaalgegevens beginnen.' }, { question: 'Kunnen we later uitbreiden?', answer: 'Je plan groeit mee met je team.' }] } }, { type: 'button', content: { text: 'Start gratis', url: '/diensten', variant: 'primary', size: 'lg' } }] }
    ],
    magazine: [
      { name: 'Over ons', slug: 'over-ons', title: 'De redactie', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Verhalen met aandacht gemaakt' } }, { type: 'text', content: { content: 'Onze redactie zoekt stemmen, ideeën en perspectieven die het dagelijks leven rijker maken.' } }, { type: 'card', content: { title: 'Onze waarden', description: 'Nieuwsgierig, zorgvuldig en altijd menselijk.' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Themas', blocks: [{ type: 'blog', content: { title: 'Alle verhalen', posts: [{ title: 'Werk dat betekenis krijgt', excerpt: 'Over aandacht, ritme en beter samenwerken.', date: '12 juni 2026', url: '#' }, { title: 'De stad als speelveld', excerpt: 'Nieuwe ideeën uit onverwachte hoeken.', date: '5 juni 2026', url: '#' }, { title: 'Kleine rituelen', excerpt: 'Waarom dagelijks herhalen helpt.', date: '28 mei 2026', url: '#' }] } }, { type: 'faq', content: { title: 'Themas', items: [{ question: 'Werk', answer: 'Ideeën over werk en maken.' }, { question: 'Leven', answer: 'Verhalen over hoe we leven.' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Redactie', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Heb je een verhaal?' } }, { type: 'text', content: { content: 'Tip ons, reageer of schrijf je in voor de nieuwsbrief.' } }, contactForm] }
    ],
    story: [
      { name: 'Over ons', slug: 'over-ons', title: 'Mijn verhaal', blocks: [{ type: 'hero', content: { headline: 'Achter de schermen', subheadline: 'De mensen, plekken en lessen die mijn werk vormen.', text_align: 'left' } }, { type: 'text', content: { content: 'Ik verzamel ideeën, maak ruimte voor aandacht en deel wat onderweg waardevol blijkt.' } }, { type: 'gallery', content: { images: [], columns: 2, gap: '1rem' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Werk', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Wat ik maak' } }, ...serviceCards, { type: 'blog', content: { title: 'Notities', posts: [{ title: 'Over langzaam werken', excerpt: 'Ruimte maken voor goed werk.', date: '12 juni 2026', url: '#' }, { title: 'Een nieuw begin', excerpt: 'Wat ik leerde van opnieuw starten.', date: '2 juni 2026', url: '#' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Samenwerken', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Vertel me wat je maakt' } }, { type: 'testimonials', content: { title: 'Mooie woorden', items: [{ quote: 'Mila brengt rust, aandacht en een goed oog mee.', name: 'Ruben Bakker', role: 'Samenwerkingspartner' }] } }, contactForm] }
    ],
    local: [
      { name: 'Over ons', slug: 'over-ons', title: 'Dichtbij', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Een vertrouwd adres in de buurt' } }, { type: 'text', content: { content: 'We kennen onze klanten bij naam en helpen graag met eerlijk advies.' } }, { type: 'card', content: { title: 'Persoonlijk', description: 'Je krijgt altijd iemand aan de lijn die met je meedenkt.' } }, { type: 'card', content: { title: 'Lokaal', description: 'We zijn er voor de buurt, elke dag opnieuw.' } }] },
      { name: 'Diensten', slug: 'diensten', title: 'Aanbod', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Kom langs of bestel vooraf' } }, ...serviceCards, { type: 'faq', content: { title: 'Openingstijden en route', items: [{ question: 'Wanneer zijn we open?', answer: 'Maandag tot en met zaterdag van 09:00 tot 18:00.' }, { question: 'Waar vind je ons?', answer: 'In het hart van de buurt, naast het plein.' }] } }] },
      { name: 'Contact', slug: 'contact', title: 'Kom langs', blocks: [{ type: 'heading', content: { level: 'h1', text: 'We horen graag van je' } }, { type: 'button', content: { text: 'Bel ons', url: 'tel:+31000000000', variant: 'primary', size: 'lg' } }, contactForm] }
    ]
  };
  return [
    { name: 'Home', slug: 'home', title: hero, blocks: homeLayouts[layout] },
    ...pageVariants[layout]
  ];
}

export const fullTemplates: Record<string, FullTemplate> = {
  photographer: { id: 'photographer', label: 'Fotograaf', description: 'Een beeldgerichte portfolio-website voor fotografen en studio’s.', category: 'Creatief', colors: ['#1f2937', '#d97706', '#fafaf9', '#292524', 'Arial, sans-serif', 'Georgia, serif', '0.25rem'], pages: standardPages('Beelden die blijven hangen', 'Fotografie voor merken, mensen en momenten die je wilt onthouden.', ['Portretfotografie', 'Branding en campagnes', 'Bruiloften en events'], [{ type: 'gallery', content: { images: [], columns: 3, gap: '1rem' } }], 'editorial', 'Lichtlijn Fotografie') },
  shop: { id: 'shop', label: 'Webshop', description: 'Een verkoopgerichte website met producten, voordelen en contact.', category: 'E-commerce', colors: ['#7c3aed', '#ec4899', '#faf5ff', '#271a3d', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem'], pages: standardPages('Alles wat je nodig hebt', 'Ontdek zorgvuldig geselecteerde producten met snelle levering en persoonlijke service.', ['Nieuwe collectie', 'Bestsellers', 'Cadeaus en bundels'], [{ type: 'pricing', content: { title: 'Populaire bundels', plans: [{ name: 'Starter', price: '€29', features: ['3 producten', 'Snelle verzending'], cta_text: 'Bekijk bundel', cta_url: '#' }, { name: 'Complete set', price: '€79', features: ['8 producten', 'Gratis verzending'], cta_text: 'Bekijk bundel', cta_url: '#' }] } }], 'commerce', 'Morrow Market') },
  gym: { id: 'gym', label: 'Sportschool', description: 'Een energieke website voor sportscholen, coaches en studio’s.', category: 'Gezondheid', colors: ['#dc2626', '#f97316', '#fff7ed', '#431407', 'Arial, sans-serif', 'Arial, sans-serif', '0.25rem'], pages: standardPages('Word sterker dan gisteren', 'Persoonlijke coaching, krachtige trainingen en een community die je motiveert.', ['Personal training', 'Groepslessen', 'Voedingsbegeleiding'], [{ type: 'pricing', content: { title: 'Lidmaatschappen', plans: [{ name: 'Basis', price: '€39 p/m', features: ['Onbeperkt trainen'], cta_text: 'Start vandaag', cta_url: '/contact' }, { name: 'Plus', price: '€69 p/m', features: ['Onbeperkt trainen', '2 coachsessies'], cta_text: 'Kies Plus', cta_url: '/contact' }] } }], 'fitness', 'Kracht Studio') },
  'real-estate': { id: 'real-estate', label: 'Makelaar', description: 'Een betrouwbare woning- en bedrijfspresentatie voor makelaars.', category: 'Zakelijk', colors: ['#075985', '#0d9488', '#f0fdfa', '#123047', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'], pages: standardPages('Een plek die bij je past', 'Persoonlijke begeleiding bij kopen, verkopen en investeren in vastgoed.', ['Woningen zoeken', 'Verkoopbegeleiding', 'Waardebepaling'], [{ type: 'blog', content: { title: 'Actueel in de markt', posts: [{ title: 'Je huis verkoopklaar maken', excerpt: 'Praktische tips voor een sterke eerste indruk.', date: '12 juni 2026', url: '#' }, { title: 'De waarde van je woning', excerpt: 'Zo komt een waardebepaling tot stand.', date: '4 juni 2026', url: '#' }] } }], 'property', 'Thuisvast Makelaars') },
  freelancer: { id: 'freelancer', label: 'Freelancer', description: 'Een persoonlijke dienstenwebsite voor zelfstandige professionals.', category: 'Persoonlijk', colors: ['#4338ca', '#06b6d4', '#eef2ff', '#1e1b4b', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'], pages: standardPages('Jouw flexibele specialist', 'Ik help teams met strategie, uitvoering en een frisse blik op complexe vraagstukken.', ['Advies en strategie', 'Projectondersteuning', 'Workshops'], [], 'consultant', 'Studio Noor') },
  'it-company': { id: 'it-company', label: 'IT-bedrijf', description: 'Een moderne B2B-site voor IT, consultancy en managed services.', category: 'Technologie', colors: ['#0f172a', '#38bdf8', '#f0f9ff', '#172033', 'Arial, sans-serif', 'Arial, sans-serif', '0.5rem'], pages: standardPages('Technologie die voor je werkt', 'Veilige, schaalbare IT-oplossingen voor organisaties die willen groeien.', ['Cloud en infrastructuur', 'Cybersecurity', 'Data en automatisering'], [{ type: 'dashboard', content: { title: 'Onze impact', stats: [{ label: 'Uptime', value: '99,99%', change: 'Betrouwbaar' }, { label: 'Klanttevredenheid', value: '9,4' }, { label: 'Actieve projecten', value: '38' }] } }], 'technology', 'Nexora IT') },
  saas: { id: 'saas', label: 'SaaS / startup', description: 'Een conversiegerichte startupsite met pricing en social proof.', category: 'Technologie', colors: ['#2563eb', '#7c3aed', '#eff6ff', '#172554', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem'], pages: standardPages('Werk slimmer, samen', 'Een eenvoudige tool voor teams die meer gedaan willen krijgen met minder gedoe.', ['Taken organiseren', 'Samenwerken', 'Inzichten krijgen'], [{ type: 'pricing', content: { title: 'Eenvoudige prijzen', plans: [{ name: 'Free', price: '€0', features: ['Voor kleine teams'], cta_text: 'Probeer gratis', cta_url: '#' }, { name: 'Team', price: '€12 p/u', features: ['Onbeperkte projecten', 'Teamrapportages'], cta_text: 'Start trial', cta_url: '#' }, { name: 'Scale', price: 'Op maat', features: ['SLA support', 'Geavanceerde beveiliging'], cta_text: 'Praat met sales', cta_url: '/contact' }] } }, { type: 'faq', content: { title: 'Vragen over het product', items: [{ question: 'Kan ik gratis starten?', answer: 'Ja, zonder betaalgegevens.' }, { question: 'Kan ik later upgraden?', answer: 'Je kunt op elk moment van plan veranderen.' }] } }], 'product', 'Flowdesk') },
  blog: { id: 'blog', label: 'Blog', description: 'Een complete redactionele website voor artikelen en nieuws.', category: 'Content', colors: ['#be123c', '#f59e0b', '#fff7ed', '#431407', 'Arial, sans-serif', 'Georgia, serif', '0.25rem'], pages: standardPages('Ideeën voor elke dag', 'Verhalen, inzichten en praktische inspiratie voor nieuwsgierige mensen.', ['Laatste artikelen', 'Thema’s', 'Over de redactie'], [{ type: 'blog', content: { title: 'Uitgelicht', posts: [{ title: 'Een goed begin', excerpt: 'Waarom kleine stappen vaak de grootste verandering brengen.', date: '12 juni 2026', url: '#' }, { title: 'Achter het verhaal', excerpt: 'Maak kennis met de mensen en ideeën achter de artikelen.', date: '5 juni 2026', url: '#' }] } }], 'magazine', 'De Dagmaker') },
  personal: { id: 'personal', label: 'Persoonlijke website', description: 'Een warme persoonlijke website met verhaal, werk en contact.', category: 'Persoonlijk', colors: ['#0f766e', '#f59e0b', '#f0fdfa', '#134e4a', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'], pages: standardPages('Welkom in mijn wereld', 'Een plek voor mijn verhaal, werk en de dingen die mij inspireren.', ['Mijn verhaal', 'Mijn werk', 'Notities'], [{ type: 'testimonials', content: { title: 'Samenwerkingen', items: [{ quote: 'Een fijne, creatieve en betrouwbare partner.', name: 'Ruben Bakker', role: 'Samenwerkingspartner' }] } }], 'story', 'Mila Verhalen') },
  'local-business': { id: 'local-business', label: 'Lokale onderneming', description: 'Een toegankelijke website voor winkels, praktijken en lokale diensten.', category: 'Lokaal', colors: ['#166534', '#ca8a04', '#fefce8', '#365314', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'], pages: standardPages('Goed geregeld, dichtbij', 'Persoonlijke service voor de buurt. Kom langs, bel of stuur ons een bericht.', ['Onze producten', 'Openingstijden', 'Route en contact'], [{ type: 'faq', content: { title: 'Praktische informatie', items: [{ question: 'Wanneer zijn jullie open?', answer: 'Maandag tot en met zaterdag van 09:00 tot 18:00.' }, { question: 'Kan ik vooraf bestellen?', answer: 'Ja, neem telefonisch of via het formulier contact op.' }] } }], 'local', 'Buurt & Co') }
};

const existingTemplateMeta: Record<string, [string, string, string, string, string, string, string]> = {
  business: ['#0f766e', '#14b8a6', '#f8fafc', '#16302b', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'],
  restaurant: ['#9f1239', '#ea580c', '#fffaf0', '#3b1f1f', 'Georgia, serif', 'Georgia, serif', '0.25rem'],
  portfolio: ['#db2777', '#f97316', '#fff7ed', '#2b1b2b', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'],
  landing: ['#4338ca', '#0891b2', '#f0fdfa', '#172033', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem']
};

for (const [id, pages] of Object.entries(templateSites)) {
  if (fullTemplates[id]) continue;
  const colors = existingTemplateMeta[id] || existingTemplateMeta.landing;
  fullTemplates[id] = {
    id,
    label: id === 'business' ? 'Bedrijf' : id === 'restaurant' ? 'Restaurant' : id === 'portfolio' ? 'Portfolio' : 'Landing page',
    description: 'Complete website-template met meerdere pagina’s en voorbeeldcontent.',
    category: 'Website',
    colors,
    pages: Object.entries(pages).map(([slug, blocks]) => ({
      name: slug === 'home' ? 'Home' : slug,
      slug,
      title: slug,
      blocks
    }))
  };
}
