import { LayoutBlock } from './layouts';
import { templateSites } from './templateSites';

export type FullTemplate = {
  id: string;
  label: string;
  description: string;
  category: string;
  pages: Array<{ name: string; slug: string; title: string; blocks: LayoutBlock[] }>;
  colors: [string, string, string, string, string, string, string];
};

const contactForm: LayoutBlock = { type: 'contact-form', content: { fields: [{ type: 'text', name: 'name', label: 'Naam', required: true }, { type: 'email', name: 'email', label: 'E-mail', required: true }, { type: 'textarea', name: 'message', label: 'Bericht', required: true }], submit_text: 'Versturen', success_message: 'Bedankt, we nemen snel contact op.' } };

function standardPages(hero: string, intro: string, services: string[], accent: LayoutBlock[] = []): FullTemplate['pages'] {
  return [
    { name: 'Home', slug: 'home', title: hero, blocks: [{ type: 'header', content: { logo: 'Jouw merk', links: [{ label: 'Over ons', url: '/over-ons' }, { label: 'Diensten', url: '/diensten' }, { label: 'Contact', url: '/contact' }], cta_text: 'Neem contact op', cta_url: '/contact' } }, { type: 'hero', content: { headline: hero, subheadline: intro, cta_text: 'Ontdek meer', cta_url: '/diensten', text_align: 'left' } }, { type: 'heading', content: { level: 'h2', text: 'Wat we bieden' } }, ...services.map(title => ({ type: 'card', content: { title, description: `Ontdek hoe ${title.toLowerCase()} je helpt om sneller en beter resultaat te behalen.`, cta_text: 'Lees meer', cta_url: '/diensten' } } as LayoutBlock)), { type: 'testimonials', content: { title: 'Wat klanten zeggen', items: [{ quote: 'Professioneel, duidelijk en precies wat we nodig hadden.', name: 'Sanne de Vries', role: 'Klant' }] } }, { type: 'cta', content: { title: 'Klaar voor de volgende stap?', text: 'Vertel ons waar je naartoe wilt.', button_text: 'Plan een gesprek', button_url: '/contact' } }, { type: 'footer', content: { text: 'Jouw merk - Samen maken we vooruitgang.', links: [{ label: 'Privacy', url: '#' }, { label: 'Contact', url: '/contact' }] } }] },
    { name: 'Over ons', slug: 'over-ons', title: 'Over ons', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Een team met aandacht voor resultaat' } }, { type: 'text', content: { content: `Wij geloven dat goede samenwerking begint met luisteren. ${intro}` } }, { type: 'card', content: { title: 'Persoonlijk', description: 'Korte lijnen, duidelijke afspraken en een aanpak die past bij jouw situatie.' } }, { type: 'card', content: { title: 'Praktisch', description: 'We vertalen ambities naar concrete stappen die vandaag al verschil maken.' } }, { type: 'faq', content: { title: 'Veelgestelde vragen', items: [{ question: 'Hoe werken jullie?', answer: 'We starten met een kennismaking en maken daarna samen een helder plan.' }, { question: 'Kan ik klein beginnen?', answer: 'Ja, iedere samenwerking kan starten met een losse sessie of eerste stap.' }] } }] },
    { name: 'Diensten', slug: 'diensten', title: 'Diensten', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Diensten die bij je passen' } }, { type: 'text', content: { content: 'Kies de ondersteuning die past bij jouw doelen, team en planning.' } }, ...services.map(title => ({ type: 'card', content: { title, description: `Een complete oplossing rondom ${title.toLowerCase()}, van eerste idee tot uitvoering.`, cta_text: 'Bespreek dit', cta_url: '/contact' } } as LayoutBlock)), ...accent] },
    { name: 'Contact', slug: 'contact', title: 'Contact', blocks: [{ type: 'heading', content: { level: 'h1', text: 'Laten we kennismaken' } }, { type: 'text', content: { content: 'Laat je gegevens achter. We reageren binnen twee werkdagen.' } }, contactForm] }
  ];
}

export const fullTemplates: Record<string, FullTemplate> = {
  photographer: { id: 'photographer', label: 'Fotograaf', description: 'Een beeldgerichte portfolio-website voor fotografen en studio’s.', category: 'Creatief', colors: ['#1f2937', '#d97706', '#fafaf9', '#292524', 'Arial, sans-serif', 'Georgia, serif', '0.25rem'], pages: standardPages('Beelden die blijven hangen', 'Fotografie voor merken, mensen en momenten die je wilt onthouden.', ['Portretfotografie', 'Branding en campagnes', 'Bruiloften en events'], [{ type: 'gallery', content: { images: [], columns: 3, gap: '1rem' } }]) },
  shop: { id: 'shop', label: 'Webshop', description: 'Een verkoopgerichte website met producten, voordelen en contact.', category: 'E-commerce', colors: ['#7c3aed', '#ec4899', '#faf5ff', '#271a3d', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem'], pages: standardPages('Alles wat je nodig hebt', 'Ontdek zorgvuldig geselecteerde producten met snelle levering en persoonlijke service.', ['Nieuwe collectie', 'Bestsellers', 'Cadeaus en bundels'], [{ type: 'pricing', content: { title: 'Populaire bundels', plans: [{ name: 'Starter', price: '€29', features: ['3 producten', 'Snelle verzending'], cta_text: 'Bekijk bundel', cta_url: '#' }, { name: 'Complete set', price: '€79', features: ['8 producten', 'Gratis verzending'], cta_text: 'Bekijk bundel', cta_url: '#' }] } }]) },
  gym: { id: 'gym', label: 'Sportschool', description: 'Een energieke website voor sportscholen, coaches en studio’s.', category: 'Gezondheid', colors: ['#dc2626', '#f97316', '#fff7ed', '#431407', 'Arial, sans-serif', 'Arial, sans-serif', '0.25rem'], pages: standardPages('Word sterker dan gisteren', 'Persoonlijke coaching, krachtige trainingen en een community die je motiveert.', ['Personal training', 'Groepslessen', 'Voedingsbegeleiding'], [{ type: 'pricing', content: { title: 'Lidmaatschappen', plans: [{ name: 'Basis', price: '€39 p/m', features: ['Onbeperkt trainen'], cta_text: 'Start vandaag', cta_url: '/contact' }, { name: 'Plus', price: '€69 p/m', features: ['Onbeperkt trainen', '2 coachsessies'], cta_text: 'Kies Plus', cta_url: '/contact' }] } }]) },
  'real-estate': { id: 'real-estate', label: 'Makelaar', description: 'Een betrouwbare woning- en bedrijfspresentatie voor makelaars.', category: 'Zakelijk', colors: ['#075985', '#0d9488', '#f0fdfa', '#123047', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'], pages: standardPages('Een plek die bij je past', 'Persoonlijke begeleiding bij kopen, verkopen en investeren in vastgoed.', ['Woningen zoeken', 'Verkoopbegeleiding', 'Waardebepaling'], [{ type: 'blog', content: { title: 'Actueel in de markt', posts: [{ title: 'Je huis verkoopklaar maken', excerpt: 'Praktische tips voor een sterke eerste indruk.', date: '12 juni 2026', url: '#' }, { title: 'De waarde van je woning', excerpt: 'Zo komt een waardebepaling tot stand.', date: '4 juni 2026', url: '#' }] } }]) },
  freelancer: { id: 'freelancer', label: 'Freelancer', description: 'Een persoonlijke dienstenwebsite voor zelfstandige professionals.', category: 'Persoonlijk', colors: ['#4338ca', '#06b6d4', '#eef2ff', '#1e1b4b', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'], pages: standardPages('Jouw flexibele specialist', 'Ik help teams met strategie, uitvoering en een frisse blik op complexe vraagstukken.', ['Advies en strategie', 'Projectondersteuning', 'Workshops'], []) },
  'it-company': { id: 'it-company', label: 'IT-bedrijf', description: 'Een moderne B2B-site voor IT, consultancy en managed services.', category: 'Technologie', colors: ['#0f172a', '#38bdf8', '#f0f9ff', '#172033', 'Arial, sans-serif', 'Arial, sans-serif', '0.5rem'], pages: standardPages('Technologie die voor je werkt', 'Veilige, schaalbare IT-oplossingen voor organisaties die willen groeien.', ['Cloud en infrastructuur', 'Cybersecurity', 'Data en automatisering'], [{ type: 'dashboard', content: { title: 'Onze impact', stats: [{ label: 'Uptime', value: '99,99%', change: 'Betrouwbaar' }, { label: 'Klanttevredenheid', value: '9,4' }, { label: 'Actieve projecten', value: '38' }] } }]) },
  saas: { id: 'saas', label: 'SaaS / startup', description: 'Een conversiegerichte startupsite met pricing en social proof.', category: 'Technologie', colors: ['#2563eb', '#7c3aed', '#eff6ff', '#172554', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem'], pages: standardPages('Werk slimmer, samen', 'Een eenvoudige tool voor teams die meer gedaan willen krijgen met minder gedoe.', ['Taken organiseren', 'Samenwerken', 'Inzichten krijgen'], [{ type: 'pricing', content: { title: 'Eenvoudige prijzen', plans: [{ name: 'Free', price: '€0', features: ['Voor kleine teams'], cta_text: 'Probeer gratis', cta_url: '#' }, { name: 'Team', price: '€12 p/u', features: ['Onbeperkte projecten', 'Teamrapportages'], cta_text: 'Start trial', cta_url: '#' }, { name: 'Scale', price: 'Op maat', features: ['SLA support', 'Geavanceerde beveiliging'], cta_text: 'Praat met sales', cta_url: '/contact' }] } }, { type: 'faq', content: { title: 'Vragen over het product', items: [{ question: 'Kan ik gratis starten?', answer: 'Ja, zonder betaalgegevens.' }, { question: 'Kan ik later upgraden?', answer: 'Je kunt op elk moment van plan veranderen.' }] } }]) },
  blog: { id: 'blog', label: 'Blog', description: 'Een complete redactionele website voor artikelen en nieuws.', category: 'Content', colors: ['#be123c', '#f59e0b', '#fff7ed', '#431407', 'Arial, sans-serif', 'Georgia, serif', '0.25rem'], pages: standardPages('Ideeën voor elke dag', 'Verhalen, inzichten en praktische inspiratie voor nieuwsgierige mensen.', ['Laatste artikelen', 'Thema’s', 'Over de redactie'], [{ type: 'blog', content: { title: 'Uitgelicht', posts: [{ title: 'Een goed begin', excerpt: 'Waarom kleine stappen vaak de grootste verandering brengen.', date: '12 juni 2026', url: '#' }, { title: 'Achter het verhaal', excerpt: 'Maak kennis met de mensen en ideeën achter de artikelen.', date: '5 juni 2026', url: '#' }] } }]) },
  personal: { id: 'personal', label: 'Persoonlijke website', description: 'Een warme persoonlijke website met verhaal, werk en contact.', category: 'Persoonlijk', colors: ['#0f766e', '#f59e0b', '#f0fdfa', '#134e4a', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'], pages: standardPages('Welkom in mijn wereld', 'Een plek voor mijn verhaal, werk en de dingen die mij inspireren.', ['Mijn verhaal', 'Mijn werk', 'Notities'], [{ type: 'testimonials', content: { title: 'Samenwerkingen', items: [{ quote: 'Een fijne, creatieve en betrouwbare partner.', name: 'Ruben Bakker', role: 'Samenwerkingspartner' }] } }]) },
  'local-business': { id: 'local-business', label: 'Lokale onderneming', description: 'Een toegankelijke website voor winkels, praktijken en lokale diensten.', category: 'Lokaal', colors: ['#166534', '#ca8a04', '#fefce8', '#365314', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'], pages: standardPages('Goed geregeld, dichtbij', 'Persoonlijke service voor de buurt. Kom langs, bel of stuur ons een bericht.', ['Onze producten', 'Openingstijden', 'Route en contact'], [{ type: 'faq', content: { title: 'Praktische informatie', items: [{ question: 'Wanneer zijn jullie open?', answer: 'Maandag tot en met zaterdag van 09:00 tot 18:00.' }, { question: 'Kan ik vooraf bestellen?', answer: 'Ja, neem telefonisch of via het formulier contact op.' }] } }]) }
};

const existingTemplateMeta: Record<string, [string, string, string, string, string, string, string]> = {
  business: ['#0f766e', '#14b8a6', '#f8fafc', '#16302b', 'Arial, sans-serif', 'Georgia, serif', '0.35rem'],
  restaurant: ['#9f1239', '#ea580c', '#fffaf0', '#3b1f1f', 'Georgia, serif', 'Georgia, serif', '0.25rem'],
  portfolio: ['#db2777', '#f97316', '#fff7ed', '#2b1b2b', 'Arial, sans-serif', 'Georgia, serif', '0.75rem'],
  landing: ['#4338ca', '#0891b2', '#f0fdfa', '#172033', 'Arial, sans-serif', 'Arial, sans-serif', '0.75rem']
};

for (const [id, pages] of Object.entries(templateSites)) {
  if (fullTemplates[id]) continue;
  const colors = existingTemplateMeta[id] || existingTemplateMeta.landing;
  fullTemplates[id] = {
    id,
    label: id === 'business' ? 'Bedrijf' : id === 'restaurant' ? 'Restaurant' : id === 'portfolio' ? 'Portfolio' : 'Landing page',
    description: 'Complete website-template met meerdere pagina’s en voorbeeldcontent.',
    category: 'Website',
    colors,
    pages: Object.entries(pages).map(([slug, blocks]) => ({
      name: slug === 'home' ? 'Home' : slug,
      slug,
      title: slug,
      blocks
    }))
  };
}
